export const productsData = {
  "Living Room": [
    {
      id: "lr-1",
      name: "The Cloud Sectional",
      price: 113900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/hero/green-chair.jpeg",
        "/assets/img/hero/green-chair-front.png",
        "/assets/img/hero/green-chair-side.png",
        "/assets/img/hero/green-chair-back.png",
      ]
    },
    {
      id: "lr-2",
      name: "Aero Lounge Chair",
      price: 228900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-2.jpg",
      ]
    },
    {
      id: "lr-3",
      name: "Oasis Coffee Table",
      price: 96900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-3.jpg",
      ]
    },
    {
      id: "lr-4",
      name: "Lumina Sofa",
      price: 130900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-4.png",
      ]
    },
    {
      id: "lr-5",
      name: "Velvet Accent Chair",
      price: 175900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:160cm\nD:200cm\nH:110cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-5.png",
      ]
    },
    {
      id: "lr-6",
      name: "Marble Center Table",
      price: 116900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:55cm\nD:60cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-6.png",
      ]
    },
    {
      id: "lr-7",
      name: "Oak TV Console",
      price: 234900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-7.jpg",
      ]
    },
    {
      id: "lr-8",
      name: "Cashmere Throw Sofa",
      price: 122900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-8.jpg",
      ]
    },
    {
      id: "lr-9",
      name: "Minimalist Bookshelf",
      price: 123900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-9.jpg",
      ]
    },
    {
      id: "lr-10",
      name: "Curved Modern Sofa",
      price: 196900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-10.jpg",
      ]
    },
    {
      id: "lr-11",
      name: "Leather Recliner",
      price: 55900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:160cm\nD:200cm\nH:110cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-11.jpg",
      ]
    },
    {
      id: "lr-12",
      name: "Glass Nested Tables",
      price: 246900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:55cm\nD:60cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-12.jpg",
      ]
    },
    {
      id: "lr-13",
      name: "Boucle Ottoman",
      price: 178900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: true,
      images: [
        "/assets/img/living-room/living-room-13.jpg",
      ]
    },
    {
      id: "lr-14",
      name: "Statement Floor Lamp",
      price: 176900,
      description: "A beautiful addition to your living room, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/living-room/living-room-14.jpg",
      ]
    },
  ],
  "Bedroom": [
    {
      id: "br-1",
      name: "Serenity Bed Frame",
      price: 235900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/bedroom/bedroom-1.jpg",
      ]
    },
    {
      id: "br-2",
      name: "Lumina Nightstand",
      price: 117900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: true,
      images: [
        "/assets/img/bedroom/bedroom-2.jpg",
      ]
    },
    {
      id: "br-3",
      name: "Oak Dresser",
      price: 150900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:160cm\nD:200cm\nH:110cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/bedroom/bedroom-3.jpg",
      ]
    },
    {
      id: "br-4",
      name: "Velvet Headboard",
      price: 238900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:55cm\nD:60cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/bedroom/bedroom-4.jpg",
      ]
    },
    {
      id: "br-5",
      name: "Minimalist Wardrobe",
      price: 165900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/bedroom/bedroom-5.jpg",
      ]
    },
    {
      id: "br-6",
      name: "Cashmere Bench",
      price: 132900,
      description: "A beautiful addition to your bedroom, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/bedroom/bedroom-6.jpg",
      ]
    },
  ],
  "Dining Area": [
    {
      id: "dn-1",
      name: "Gather Dining Table",
      price: 129900,
      description: "A beautiful addition to your dining area, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/dining-room/dining-room-1.jpg",
      ]
    },
    {
      id: "dn-2",
      name: "Silhouette Dining Chair",
      price: 85900,
      description: "A beautiful addition to your dining area, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/dining-room/dining-room-2.jpg",
      ]
    },
    {
      id: "dn-3",
      name: "Walnut Credenza",
      price: 159900,
      description: "A beautiful addition to your dining area, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:160cm\nD:200cm\nH:110cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/dining-room/dining-room-3.jpg",
      ]
    },
    {
      id: "dn-4",
      name: "Marble Dining Table",
      price: 222900,
      description: "A beautiful addition to your dining area, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:55cm\nD:60cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/dining-room/dining-room-4.jpg",
      ]
    },
    {
      id: "dn-5",
      name: "Boucle Dining Chair",
      price: 143900,
      description: "A beautiful addition to your dining area, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: true,
      images: [
        "/assets/img/dining-room/dining-room-5.jpg",
      ]
    },
  ],
  "Home Office": [
    {
      id: "ho-1",
      name: "Focus Executive Desk",
      price: 95900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-1.jpg",
      ]
    },
    {
      id: "ho-2",
      name: "Ergo Task Chair",
      price: 80900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-2.jpg",
      ]
    },
    {
      id: "ho-3",
      name: "Minimalist Bookshelf",
      price: 124900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-3.jpg",
      ]
    },
    {
      id: "ho-4",
      name: "Oak Filing Cabinet",
      price: 110900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:160cm\nD:200cm\nH:110cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-4.jpg",
      ]
    },
    {
      id: "ho-5",
      name: "Standing Desk",
      price: 148900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Walnut veneer\nengineered wood",
      finish: "Tempered glass & steel",
      dimensions: "W:55cm\nD:60cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-5.jpg",
      ]
    },
    {
      id: "ho-6",
      name: "Leather Office Chair",
      price: 51900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Solid ash wood\nhigh-resilience sponge",
      finish: "Premium bouclé fabric",
      dimensions: "W:80cm\nD:85cm\nH:97cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-6.jpg",
      ]
    },
    {
      id: "ho-7",
      name: "Floating Wall Shelves",
      price: 159900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Mahogany frame\nmemory foam core",
      finish: "Top-grain leather",
      dimensions: "W:210cm\nD:95cm\nH:85cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: false,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-7.jpg",
      ]
    },
    {
      id: "ho-8",
      name: "Modern Table Lamp",
      price: 230900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Brushed steel\npolyurethane foam",
      finish: "Velvet upholstery",
      dimensions: "W:120cm\nD:60cm\nH:45cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: false,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-8.jpg",
      ]
    },
    {
      id: "ho-9",
      name: "Walnut Meeting Table",
      price: 245900,
      description: "A beautiful addition to your home office, designed with elegant proportions and premium materials.",
      structure: "Oak wood base\ngoose down blend",
      finish: "Matte lacquer",
      dimensions: "W:90cm\nD:90cm\nH:105cm",
      type: "Furniture",
      color: "Neutral",
      bestSeller: true,
      isNew: true,
      featured: false,
      images: [
        "/assets/img/home-office/home-office-9.jpg",
      ]
    },
  ],
};

// Flattened list for the all products grid with category injected
export const allProducts = Object.keys(productsData).flatMap((category) => 
  productsData[category].map((product) => ({
    ...product,
    category
  }))
);
